namespace: ansible_collection
name: dep_collection2
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: null
documentation: null
homepage: null
issues: null
